name: Multi node test workflow
# This workflow is triggered on pull requests to main
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    # Job name
    name: Build Index Management
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      # dependencies: OpenSearch
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: '1.x'
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: ./gradlew publishToMavenLocal
      # dependencies: common-utils
      - name: Checkout common-utils
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/common-utils'
          path: common-utils
          ref: 'main'
      - name: Build common-utils
        working-directory: ./common-utils
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.1.0-SNAPSHOT
      # index-management
      - name: Checkout Branch
        uses: actions/checkout@v2
      # dependencies: job-scheduler
      - name: Checkout job-scheduler
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/job-scheduler'
          path: job-scheduler
          ref: 'main'
      - name: Build job-scheduler
        working-directory: ./job-scheduler
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.1.0-SNAPSHOT
      - name: Assemble job-scheduler
        working-directory: ./job-scheduler
        run: |
          ./gradlew assemble -Dopensearch.version=1.1.0-SNAPSHOT
          mkdir -p ../src/test/resources/job-scheduler
          cp ./build/distributions/*.zip ../src/test/resources/job-scheduler
          ls ../src/test/resources/job-scheduler        
      # dependencies: notifications
      - name: Checkout notifications
        uses: actions/checkout@v2
        with:
          repository: 'dblock/notifications'
          path: notifications
          ref: 'fix-snapshot-build'
      - name: Build notifications
        working-directory: ./notifications/notifications
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.1.0-SNAPSHOT
      - name: Assemble notifications
        working-directory: ./notifications/notifications
        run: |
          ./gradlew assemble -Dopensearch.version=1.1.0-SNAPSHOT
          mkdir -p ../../src/test/resources/notifications
          cp ./notifications/build/distributions/*.zip ../../src/test/resources/notifications
          ls ../../src/test/resources/notifications
      - name: Run integration tests with multi node config
        run: ./gradlew integTest -PnumNodes=3 -Dopensearch.version=1.1.0-SNAPSHOT
      - name: Upload failed logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: build/testclusters/integTest-*/logs/*
